/* Automatically generated by './build/bin/build-entry.js' */

import ComPagination from '../packages/pagination/index.js';
import ComDialog from '../packages/dialog/index.js';
import ComAutocomplete from '../packages/autocomplete/index.js';
import ComDropdown from '../packages/dropdown/index.js';
import ComDropdownMenu from '../packages/dropdown-menu/index.js';
import ComDropdownItem from '../packages/dropdown-item/index.js';
import ComMenu from '../packages/menu/index.js';
import ComSubmenu from '../packages/submenu/index.js';
import ComMenuItem from '../packages/menu-item/index.js';
import ComMenuItemGroup from '../packages/menu-item-group/index.js';
import ComInput from '../packages/input/index.js';
import ComInputNumber from '../packages/input-number/index.js';
import ComRadio from '../packages/radio/index.js';
import ComRadioGroup from '../packages/radio-group/index.js';
import ComRadioButton from '../packages/radio-button/index.js';
import ComCheckbox from '../packages/checkbox/index.js';
import ComCheckboxButton from '../packages/checkbox-button/index.js';
import ComCheckboxGroup from '../packages/checkbox-group/index.js';
import ComSwitch from '../packages/switch/index.js';
import ComSelect from '../packages/select/index.js';
import ComOption from '../packages/option/index.js';
import ComOptionGroup from '../packages/option-group/index.js';
import ComButton from '../packages/button/index.js';
import ComButtonGroup from '../packages/button-group/index.js';
import ComTable from '../packages/table/index.js';
import ComTableColumn from '../packages/table-column/index.js';
import ComDatePicker from '../packages/date-picker/index.js';
import ComTimeSelect from '../packages/time-select/index.js';
import ComTimePicker from '../packages/time-picker/index.js';
import ComPopover from '../packages/popover/index.js';
import ComTooltip from '../packages/tooltip/index.js';
import ComMessageBox from '../packages/message-box/index.js';
import ComBreadcrumb from '../packages/breadcrumb/index.js';
import ComBreadcrumbItem from '../packages/breadcrumb-item/index.js';
import ComForm from '../packages/form/index.js';
import ComFormItem from '../packages/form-item/index.js';
import ComTabs from '../packages/tabs/index.js';
import ComTabPane from '../packages/tab-pane/index.js';
import ComTag from '../packages/tag/index.js';
import ComTree from '../packages/tree/index.js';
import ComAlert from '../packages/alert/index.js';
import ComNotification from '../packages/notification/index.js';
import ComSlider from '../packages/slider/index.js';
import ComLoading from '../packages/loading/index.js';
import ComIcon from '../packages/icon/index.js';
import ComRow from '../packages/row/index.js';
import ComCol from '../packages/col/index.js';
import ComUpload from '../packages/upload/index.js';
import ComProgress from '../packages/progress/index.js';
import ComSpinner from '../packages/spinner/index.js';
import ComMessage from '../packages/message/index.js';
import ComBadge from '../packages/badge/index.js';
import ComCard from '../packages/card/index.js';
import ComRate from '../packages/rate/index.js';
import ComSteps from '../packages/steps/index.js';
import ComStep from '../packages/step/index.js';
import ComCarousel from '../packages/carousel/index.js';
import ComScrollbar from '../packages/scrollbar/index.js';
import ComCarouselItem from '../packages/carousel-item/index.js';
import ComCollapse from '../packages/collapse/index.js';
import ComCollapseItem from '../packages/collapse-item/index.js';
import ComCascader from '../packages/cascader/index.js';
import ComColorPicker from '../packages/color-picker/index.js';
import ComTransfer from '../packages/transfer/index.js';
import ComContainer from '../packages/container/index.js';
import ComHeader from '../packages/header/index.js';
import ComAside from '../packages/aside/index.js';
import ComMain from '../packages/main/index.js';
import ComFooter from '../packages/footer/index.js';
import ComTimeline from '../packages/timeline/index.js';
import ComTimelineItem from '../packages/timeline-item/index.js';
import ComLink from '../packages/link/index.js';
import ComDivider from '../packages/divider/index.js';
import ComImage from '../packages/image/index.js';
import ComCalendar from '../packages/calendar/index.js';
import ComBacktop from '../packages/backtop/index.js';
import ComInfiniteScroll from '../packages/infinite-scroll/index.js';
import ComPageHeader from '../packages/page-header/index.js';
import ComCascaderPanel from '../packages/cascader-panel/index.js';
import ComAvatar from '../packages/avatar/index.js';
import ComDrawer from '../packages/drawer/index.js';
import ComPopconfirm from '../packages/popconfirm/index.js';
import locale from 'element-ui/src/locale';
import CollapseTransition from 'element-ui/src/transitions/collapse-transition';

const components = [
  ComPagination,
  ComDialog,
  ComAutocomplete,
  ComDropdown,
  ComDropdownMenu,
  ComDropdownItem,
  ComMenu,
  ComSubmenu,
  ComMenuItem,
  ComMenuItemGroup,
  ComInput,
  ComInputNumber,
  ComRadio,
  ComRadioGroup,
  ComRadioButton,
  ComCheckbox,
  ComCheckboxButton,
  ComCheckboxGroup,
  ComSwitch,
  ComSelect,
  ComOption,
  ComOptionGroup,
  ComButton,
  ComButtonGroup,
  ComTable,
  ComTableColumn,
  ComDatePicker,
  ComTimeSelect,
  ComTimePicker,
  ComPopover,
  ComTooltip,
  ComBreadcrumb,
  ComBreadcrumbItem,
  ComForm,
  ComFormItem,
  ComTabs,
  ComTabPane,
  ComTag,
  ComTree,
  ComAlert,
  ComSlider,
  ComIcon,
  ComRow,
  ComCol,
  ComUpload,
  ComProgress,
  ComSpinner,
  ComBadge,
  ComCard,
  ComRate,
  ComSteps,
  ComStep,
  ComCarousel,
  ComScrollbar,
  ComCarouselItem,
  ComCollapse,
  ComCollapseItem,
  ComCascader,
  ComColorPicker,
  ComTransfer,
  ComContainer,
  ComHeader,
  ComAside,
  ComMain,
  ComFooter,
  ComTimeline,
  ComTimelineItem,
  ComLink,
  ComDivider,
  ComImage,
  ComCalendar,
  ComBacktop,
  ComPageHeader,
  ComCascaderPanel,
  ComAvatar,
  ComDrawer,
  ComPopconfirm,
  CollapseTransition
];

const install = function(Vue, opts = {}) {
  locale.use(opts.locale);
  locale.i18n(opts.i18n);

  components.forEach(component => {
    Vue.component(component.name, component);
  });

  Vue.use(ComInfiniteScroll);
  Vue.use(ComLoading.directive);

  Vue.prototype.$ELEMENT = {
    size: opts.size || '',
    zIndex: opts.zIndex || 2000
  };

  Vue.prototype.$loading = ComLoading.service;
  Vue.prototype.$msgbox = ComMessageBox;
  Vue.prototype.$alert = ComMessageBox.alert;
  Vue.prototype.$confirm = ComMessageBox.confirm;
  Vue.prototype.$prompt = ComMessageBox.prompt;
  Vue.prototype.$notify = ComNotification;
  Vue.prototype.$message = ComMessage;

};

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}

export default {
  version: '2.13.0',
  locale: locale.use,
  i18n: locale.i18n,
  install,
  CollapseTransition,
  ComLoading,
  ComPagination,
  ComDialog,
  ComAutocomplete,
  ComDropdown,
  ComDropdownMenu,
  ComDropdownItem,
  ComMenu,
  ComSubmenu,
  ComMenuItem,
  ComMenuItemGroup,
  ComInput,
  ComInputNumber,
  ComRadio,
  ComRadioGroup,
  ComRadioButton,
  ComCheckbox,
  ComCheckboxButton,
  ComCheckboxGroup,
  ComSwitch,
  ComSelect,
  ComOption,
  ComOptionGroup,
  ComButton,
  ComButtonGroup,
  ComTable,
  ComTableColumn,
  ComDatePicker,
  ComTimeSelect,
  ComTimePicker,
  ComPopover,
  ComTooltip,
  ComMessageBox,
  ComBreadcrumb,
  ComBreadcrumbItem,
  ComForm,
  ComFormItem,
  ComTabs,
  ComTabPane,
  ComTag,
  ComTree,
  ComAlert,
  ComNotification,
  ComSlider,
  ComIcon,
  ComRow,
  ComCol,
  ComUpload,
  ComProgress,
  ComSpinner,
  ComMessage,
  ComBadge,
  ComCard,
  ComRate,
  ComSteps,
  ComStep,
  ComCarousel,
  ComScrollbar,
  ComCarouselItem,
  ComCollapse,
  ComCollapseItem,
  ComCascader,
  ComColorPicker,
  ComTransfer,
  ComContainer,
  ComHeader,
  ComAside,
  ComMain,
  ComFooter,
  ComTimeline,
  ComTimelineItem,
  ComLink,
  ComDivider,
  ComImage,
  ComCalendar,
  ComBacktop,
  ComInfiniteScroll,
  ComPageHeader,
  ComCascaderPanel,
  ComAvatar,
  ComDrawer,
  ComPopconfirm
};
